apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "electricity-comparison.fullname" . }}-config
  labels:
    {{- include "electricity-comparison.labels" . | nindent 4 }}
data:
  FLASK_APP: {{ .Values.env.FLASK_APP | quote }}
  FLASK_DEBUG: {{ .Values.env.FLASK_DEBUG | quote }}
  # Add other non-sensitive configuration here
