apiVersion: v1
kind: Secret
metadata:
  name: {{ include "electricity-comparison.fullname" . }}-db
  labels:
    {{- include "electricity-comparison.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secret.databaseUrl | b64enc | quote }}
